import java.awt.Color;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yalap
 */
public class issueBook extends javax.swing.JFrame {

    genre genre = new genre();
    functionClass func = new functionClass();
    member member = new member();
    issue_Book issue = new issue_Book();
    /**
     * Creates new form issueBook
     */
    
    //These variable will help us check if book & member exist or not.
    boolean bookExist = false;
    boolean memberExist = false;
    
    public issueBook() {
        initComponents();
        
        //Centre this form
        this.setLocationRelativeTo(null);
        
        //Add border to the panel [108,122,137]
        Border panelHeaderBoder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(108,122,137));
        //  Video - 10... 22:36
        //jPanel1.setBorder(panelHeaderBorder);
        
        //Display image in the top
//      func.displayImage(90, 60, null, "location", jLabel_FormTitle);        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_CloseForm = new javax.swing.JLabel();
        jLabel_IssueDate = new javax.swing.JLabel();
        jLabel_BookID = new javax.swing.JLabel();
        jButton_issueBook = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jButton_SearchBook = new javax.swing.JButton();
        jLabel_BookName = new javax.swing.JLabel();
        jButton_SearchMember = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Available = new javax.swing.JLabel();
        jLabel_MemberID = new javax.swing.JLabel();
        jLabel_MemberFullName = new javax.swing.JLabel();
        jLabel_Note = new javax.swing.JLabel();
        jSpinner_getMemberID = new javax.swing.JSpinner();
        jSpinner_getBookID = new javax.swing.JSpinner();
        jLabel_ReturnDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();
        jDateChooser_IssueDate = new com.toedter.calendar.JDateChooser();
        jDateChooser_ReturnDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Header.setBackground(new java.awt.Color(108, 122, 137));

        jLabel1.setBackground(new java.awt.Color(108, 122, 137));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Issue Book");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(108, 122, 137));

        jLabel_CloseForm.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_CloseForm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_CloseForm.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("X");
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel_IssueDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_IssueDate.setText("Issue Date:");

        jLabel_BookID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_BookID.setText("Enter Book ID:");

        jButton_issueBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_issueBook.setText("Issue");
        jButton_issueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_issueBookActionPerformed(evt);
            }
        });

        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_SearchBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_SearchBook.setText("Search Book");
        jButton_SearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchBookActionPerformed(evt);
            }
        });

        jLabel_BookName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel_BookName.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_BookName.setText("Book Name:");
        jLabel_BookName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BookNameMouseClicked(evt);
            }
        });

        jButton_SearchMember.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_SearchMember.setText("Search Member");
        jButton_SearchMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchMemberActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Is the book available:");

        jLabel_Available.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel_Available.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_Available.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Available.setText("Yes / No");

        jLabel_MemberID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_MemberID.setText("Enter Member ID:");

        jLabel_MemberFullName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel_MemberFullName.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_MemberFullName.setText("Member Full-Name:");

        jLabel_Note.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Note.setText("Note:");

        jSpinner_getMemberID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSpinner_getBookID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_ReturnDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_ReturnDate.setText("Return Date:");

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_MemberID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel_MemberFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinner_getMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_SearchMember, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_SearchBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_issueBook, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_Available, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(165, 165, 165))))
                                    .addComponent(jLabel_Note, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_BookID)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSpinner_getBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel_BookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_BookID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_getBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SearchBook))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_BookName)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_SearchMember)
                    .addComponent(jLabel_MemberID)
                    .addComponent(jSpinner_getMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_MemberFullName)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Available, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_IssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Note, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_issueBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        //Close the window
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_issueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_issueBookActionPerformed
        //issue a book
        int _book_id = (int) jSpinner_getBookID.getValue();
        int _member_id = (int) jSpinner_getMemberID.getValue();
        String _note = jTextArea_Note.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");        

        try{
            String issue_date = dateFormat.format(jDateChooser_IssueDate.getDate());
            String return_date = dateFormat.format(jDateChooser_ReturnDate.getDate());
            
            //Before Issuing a book we need to check
            //If the return date same as the issue date
            Date issDate = dateFormat.parse(issue_date);
            Date rtnDate = dateFormat.parse(return_date);

            //We need to check if Book & Member exist or not.
            if(!bookExist){
                JOptionPane.showMessageDialog(null, "You need to check if Book exist or not, by clicking the SEARCH BOOK button", "Check if the Book Exist", 2);
            }
            else if(! memberExist){
                JOptionPane.showMessageDialog(null, "You need to check if Member exist or not, by clicking the SEARCH MEMBER button", "Check if the Member Exist", 2);
            }
            else if(!issue.checkBookAvailability(_book_id)){
                JOptionPane.showMessageDialog(null, "This book isn't available right now", "Book Not Available", 2);
            }
            else if(rtnDate.before(issDate)){
                JOptionPane.showMessageDialog(null, "The Return Date must be AFTER Issue Date.", "Wrong Return Date.", 2);
            }
            else{
                issue.addIssue(_book_id, _member_id, "ISSUED", issue_date, return_date, _note);
                
                //Reset Fields
                jSpinner_getBookID.setValue(0);
                jSpinner_getMemberID.setValue(0);
                jLabel_BookName.setText("Book Name");
                jLabel_MemberFullName.setText("Member Full Name");
                jLabel_Available.setText("YES/NO");
                jLabel_Available.setForeground(new Color(51, 102, 255));
                jDateChooser_IssueDate.setDate(null);
                jDateChooser_ReturnDate.setDate(null);
                jTextArea_Note.setText("");
                bookExist = false;
                memberExist = false;
            }
        } catch(HeadlessException | NullPointerException | ParseException ex){
            JOptionPane.showMessageDialog(null, "Select Issue Date & Return Date", "Select Date", 2);
        }
    }//GEN-LAST:event_jButton_issueBookActionPerformed

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
        //Close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void jButton_SearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchBookActionPerformed
        //Get the BookID
        int BookID = (int) jSpinner_getBookID.getValue();

        try{
            genre selectedBook = genre.getBookById(BookID);
            
            if(selectedBook != null){
                //If Book exist.
                jLabel_BookName.setText(selectedBook.getName());
                
                //Set the book exist to true;
                bookExist  = true;
                
                //Display availability
                if(issue.checkBookAvailability(BookID)){
                    jLabel_Available.setText("YES");
                    jLabel_Available.setForeground(Color.green);
                }
                else{
                    jLabel_Available.setText("NO");
                    jLabel_Available.setForeground(Color.red);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "This book doesn't exist.", "Book Not Found.", 2);
                jLabel_BookName.setText("Book Name");
                bookExist = false;
                jLabel_Available.setText("YES/NO");
                jLabel_Available.setForeground(new Color(51, 102, 255));
            }
        }   catch(Exception e){
            Logger.getLogger(issueBook.class.getName()).log(Level.SEVERE,null, e);
        }      
    }//GEN-LAST:event_jButton_SearchBookActionPerformed

    
    
    
    private void jButton_SearchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchMemberActionPerformed
        //Get the memberID
        int memberID = (int) jSpinner_getMemberID.getValue();

        try{
            //get the member ID
            member selectedMember = member.getMemberById(memberID);
            
                if(selectedMember != null){
                    //If Member exist.
                    jLabel_MemberFullName.setText(selectedMember.getName());
                    
                    //Set the member exist to true;
                    memberExist  = true;
                }
                else{
                    //If the member doesnt exist
                    JOptionPane.showMessageDialog(null, "Member doesn't exist", "Member not found", 2);
                    jLabel_MemberFullName.setText("Member Full Name");
                    memberExist = false;
                }
            }   catch(Exception e){
                Logger.getLogger(issueBook.class.getName()).log(Level.SEVERE,null, e);
            }     
    }//GEN-LAST:event_jButton_SearchMemberActionPerformed

    private void jLabel_BookNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_BookNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_SearchBook;
    private javax.swing.JButton jButton_SearchMember;
    private javax.swing.JButton jButton_issueBook;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser_IssueDate;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Available;
    private javax.swing.JLabel jLabel_BookID;
    private javax.swing.JLabel jLabel_BookName;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_IssueDate;
    private javax.swing.JLabel jLabel_MemberFullName;
    private javax.swing.JLabel jLabel_MemberID;
    private javax.swing.JLabel jLabel_Note;
    private javax.swing.JLabel jLabel_ReturnDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_getBookID;
    private javax.swing.JSpinner jSpinner_getMemberID;
    private javax.swing.JTextArea jTextArea_Note;
    // End of variables declaration//GEN-END:variables
}
