
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

//import Images.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yalap
 */
public class manageMember extends javax.swing.JFrame {

    /**
     * Creates new form manageGenre
     */
    
    member member = new member();
    
    public manageMember() {
        initComponents();
        
        //center  this page.
        this.setLocationRelativeTo(null);
        
        //Add gray broder to the panel.
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.BLUE);
        jPanel1.setBorder(panelHeaderBorder);

        //Customize the table
        jTable_Member.setSelectionBackground(new Color(249, 105, 14));
        jTable_Member.setSelectionForeground(Color.white);
        jTable_Member.setRowHeight(30);
        jTable_Member.setShowGrid(true);
        jTable_Member.setBackground(new Color(240, 240, 240));
        
        //Customize the table header row
        jTable_Member.getTableHeader().setBackground(new Color(42, 187, 155));
        jTable_Member.getTableHeader().setForeground(Color.white);
        jTable_Member.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 20));
        jTable_Member.getTableHeader().setOpaque(false);
        
        //Hide the jLabel "Empty name messahe"
        jLabel_EmptyName.setVisible(false);
        
        populateJTableWithMember();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Name4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jLabel_CloseForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_ID = new javax.swing.JTextField();
        jButton_Edit = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Member = new javax.swing.JTable();
        jLabel_EmptyName = new javax.swing.JLabel();
        jTextField_MotherName = new javax.swing.JTextField();
        jLabel_AuthorName = new javax.swing.JLabel();
        jTextField_emailID = new javax.swing.JTextField();
        jLabel_Quantity = new javax.swing.JLabel();
        jTextField_contactNO = new javax.swing.JTextField();
        jLabel_Publisher = new javax.swing.JLabel();
        jTextField_Gender = new javax.swing.JTextField();
        jLabel_Publisher1 = new javax.swing.JLabel();

        jTextField_Name4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_Name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Name4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Publisher:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_FormTitle.setBackground(java.awt.Color.gray);
        jLabel_FormTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setText("Manage Members");
        jLabel_FormTitle.setOpaque(true);

        jLabel_CloseForm.setBackground(java.awt.Color.gray);
        jLabel_CloseForm.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel_CloseForm.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("X");
        jLabel_CloseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        jTextField_Name.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jTextField_ID.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });

        jButton_Edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jTable_Member.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable_Member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_MemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Member);

        jLabel_EmptyName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_EmptyName.setForeground(new java.awt.Color(253, 0, 0));
        jLabel_EmptyName.setText("* Enter student's name");
        jLabel_EmptyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EmptyNameMouseClicked(evt);
            }
        });

        jTextField_MotherName.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jTextField_MotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MotherNameActionPerformed(evt);
            }
        });

        jLabel_AuthorName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_AuthorName.setText("Mother's Name:");

        jTextField_emailID.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jTextField_emailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailIDActionPerformed(evt);
            }
        });

        jLabel_Quantity.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_Quantity.setText("Email ID:");

        jTextField_contactNO.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField_contactNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_contactNOActionPerformed(evt);
            }
        });

        jLabel_Publisher.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_Publisher.setText("Contact No.:");

        jTextField_Gender.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GenderActionPerformed(evt);
            }
        });

        jLabel_Publisher1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_Publisher1.setText("Gender:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_AuthorName)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel_Quantity)
                            .addComponent(jLabel_Publisher)
                            .addComponent(jLabel_Publisher1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Gender, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jTextField_contactNO, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jTextField_MotherName, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_emailID, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jLabel_EmptyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_EmptyName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_AuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_MotherName, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_emailID, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_contactNO, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Publisher1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_MotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MotherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MotherNameActionPerformed

    private void jLabel_EmptyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EmptyNameMouseClicked
        // TODO add your handling code here:

        //Hide this jLabel on click.
        jLabel_EmptyName.setVisible(false);
    }//GEN-LAST:event_jLabel_EmptyNameMouseClicked

    private void jTable_MemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_MemberMouseClicked
        // TODO add your handling code here:

        //Display the selected genre.
        //Get the selected row index
        int index = jTable_Member.getSelectedRow();

        //Get values
        String id = jTable_Member.getValueAt(index, 0).toString();
        String name = jTable_Member.getValueAt(index, 1).toString();
        String motherName = jTable_Member.getValueAt(index, 2).toString();
        String emailID = jTable_Member.getValueAt(index, 3).toString();
        String contactNo = jTable_Member.getValueAt(index, 4).toString();
        String Gender = jTable_Member.getValueAt(index, 5).toString();

        //Show data in textFields
        jTextField_ID.setText(id);
        jTextField_Name.setText(name);
        jTextField_MotherName.setText(motherName);
        jTextField_emailID.setText(emailID);
        jTextField_contactNO.setText(contactNo);
        jTextField_Gender.setText(Gender);
    }//GEN-LAST:event_jTable_MemberMouseClicked

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed

        //Delete the selected group.
        try{
            int id = Integer.valueOf(jTextField_ID.getText());
            member.removeMember(id);

            //Refresh the jTable book
            populateJTableWithMember();

            //Clear the text from the textField
            jTextField_ID.setText("");
            jTextField_Name.setText("");
            jTextField_MotherName.setText("");
            jTextField_emailID.setText("");
            jTextField_contactNO.setText("");
            jTextField_Gender.setText("");
        } catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Invalid Member ID - " + ex.getMessage(), "ERROR", 0);
        }

    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        //Add a new genre
        //String name = jTextField_Name.getText();
        String id = jTextField_ID.getText();
        String name = jTextField_Name.getText();
        String motherName = jTextField_MotherName.getText();
        String emailID = jTextField_emailID.getText();
        String contactNo = jTextField_contactNO.getText();
        String Gender = jTextField_Gender.getText();

        //Check if  the textField is empty.
        if(name.isEmpty()){
            //System.out.println("Empty");
            jLabel_EmptyName.setVisible(true);
        }

        //Check if  the textField is not empty.
        else{
            member.addMember(id, name, motherName, emailID, contactNo, Gender);

            //Refresh the jTable book
            populateJTableWithMember();
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        // TODO add your handling code here:
        String name = jTextField_Name.getText();
        String motherName = jTextField_MotherName.getText();
        String emailID = jTextField_emailID.getText();
        String contactNo = jTextField_contactNO.getText();
        String Gender = jTextField_Gender.getText();


        //Check if  the textField is empty.
        if(name.isEmpty()){
            //System.out.println("Empty");
            jLabel_EmptyName.setVisible(true);
        }

        //Check if  the textField is not empty.
        else{
            try{
                String id = jTextField_ID.getText();
                member.editMember(id, name, motherName, emailID, contactNo, Gender);

                //Refresh the jTable book
                populateJTableWithMember();
            } catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(null, "Invalid Member ID - " + ex.getMessage(), "ERROR", 0);
            }
        }
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
        //Close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void jTextField_emailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailIDActionPerformed

    private void jTextField_contactNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_contactNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_contactNOActionPerformed

    private void jTextField_Name4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Name4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Name4ActionPerformed

    private void jTextField_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GenderActionPerformed

    //Create a function to populate the jTable with books.
    public void populateJTableWithMember(){
        ArrayList<member> memberList = member.memberList();
        
        //jTable columns
        String[] colName = {"ID", "NAME", "Mother's Name", "email ID", "Contact No.", "Gender"};
        
        //row
        Object[][] row = new Object[memberList.size()][colName.length];
        
        for(int i = 0; i < memberList.size(); i++){
            row[i][0] = memberList.get(i).getId();
            row[i][1] = memberList.get(i).getName();
            row[i][2] = memberList.get(i).getMotherName();
            row[i][3] = memberList.get(i).getEmailID();
            row[i][4] = memberList.get(i).getContactNo();
            row[i][5] = memberList.get(i).getGender();
        }
        
        DefaultTableModel model = new DefaultTableModel(row, colName);
        jTable_Member.setModel(model);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_AuthorName;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_EmptyName;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JLabel jLabel_Publisher;
    private javax.swing.JLabel jLabel_Publisher1;
    private javax.swing.JLabel jLabel_Quantity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Member;
    private javax.swing.JTextField jTextField_Gender;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_MotherName;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Name4;
    private javax.swing.JTextField jTextField_contactNO;
    private javax.swing.JTextField jTextField_emailID;
    // End of variables declaration//GEN-END:variables
}
