import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yalap
 */
public class returnBook extends javax.swing.JFrame {

    genre genre = new genre();
    functionClass func = new functionClass();
    member member = new member();
    issue_Book issue = new issue_Book();
    /**
     * Creates new form issueBook
     */
    
    //These variable will help us check if book & member exist or not.
    boolean bookExist = false;
    boolean memberExist = false;
    
    public returnBook() {
        initComponents();
        
        //Centre this form
        this.setLocationRelativeTo(null);
        
        //Add border to the panel [108,122,137]
        Border panelHeaderBoder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(108,122,137));
        
        //Customze the jTable
        func.customTable(jTable_ReturnBook);
        
        //Customize the jTable Header row
        func.customTableHeader(jTable_ReturnBook, new Color(34, 167, 240), 13);

        //Populate jTable with issued books table
        populateJTableWithIssuedBook("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_CloseForm = new javax.swing.JLabel();
        jLabel_IssueDate = new javax.swing.JLabel();
        jLabel_BookID = new javax.swing.JLabel();
        jButton_Delete = new javax.swing.JButton();
        jButton_Lost = new javax.swing.JButton();
        jLabel_BookName = new javax.swing.JLabel();
        jLabel_MemberID = new javax.swing.JLabel();
        jLabel_MemberFullName = new javax.swing.JLabel();
        jLabel_Note = new javax.swing.JLabel();
        jSpinner_getMemberID = new javax.swing.JSpinner();
        jSpinner_getBookID = new javax.swing.JSpinner();
        jLabel_ReturnDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();
        jDateChooser_IssueDate = new com.toedter.calendar.JDateChooser();
        jDateChooser_ReturnDate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ReturnBook = new javax.swing.JTable();
        jComboBox_bookStatus = new javax.swing.JComboBox<>();
        jLabel_IssueDate1 = new javax.swing.JLabel();
        jButton_returnBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Header.setBackground(new java.awt.Color(108, 122, 137));

        jLabel1.setBackground(new java.awt.Color(108, 122, 137));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return Book");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(108, 122, 137));

        jLabel_CloseForm.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_CloseForm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_CloseForm.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("X");
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel_IssueDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_IssueDate.setText("Issue Date:");

        jLabel_BookID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_BookID.setText("Enter Book ID:");

        jButton_Delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_Lost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Lost.setText("Lost");
        jButton_Lost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LostActionPerformed(evt);
            }
        });

        jLabel_BookName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel_BookName.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_BookName.setText("Book Name:");
        jLabel_BookName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BookNameMouseClicked(evt);
            }
        });

        jLabel_MemberID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_MemberID.setText("Enter Member ID:");

        jLabel_MemberFullName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel_MemberFullName.setForeground(new java.awt.Color(51, 102, 255));
        jLabel_MemberFullName.setText("Member Full-Name:");

        jLabel_Note.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Note.setText("Note:");

        jSpinner_getMemberID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSpinner_getBookID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel_ReturnDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_ReturnDate.setText("Return Date:");

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note);

        jTable_ReturnBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_ReturnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ReturnBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_ReturnBook);

        jComboBox_bookStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_bookStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Issued", "RETURED", "LOST" }));
        jComboBox_bookStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_bookStatusActionPerformed(evt);
            }
        });

        jLabel_IssueDate1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_IssueDate1.setText("Select Book Status:");

        jButton_returnBook.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_returnBook.setText("Return");
        jButton_returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_returnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_BookID)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner_getBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_BookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Note, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel_MemberID)
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSpinner_getMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_MemberFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_IssueDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox_bookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_returnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Lost, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_BookID)
                            .addComponent(jSpinner_getBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_BookName)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_MemberID)
                            .addComponent(jSpinner_getMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MemberFullName)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_bookStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_IssueDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Note, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_Lost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_returnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LostActionPerformed
        //Book is lost 
        int _book_id = (int) jSpinner_getBookID.getValue();
        int _member_id = (int) jSpinner_getMemberID.getValue();
        String _note = jTextArea_Note.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");       

        try{
            String return_date = dateFormat.format(jDateChooser_ReturnDate.getDate());
            String issue_date = dateFormat.format(jDateChooser_IssueDate.getDate());
           
            issue.updateIssue(_book_id, _member_id, "LOST", issue_date, return_date, _note);
            
            //Reducing QUANTITY of book by 1
            float quantity = new genre().getBookById(_book_id).getQuantity();
            genre.setQuantityMinusOne(_book_id, quantity-1);
                
            //Reset Fields
            jSpinner_getBookID.setValue(0);
            jSpinner_getMemberID.setValue(0);
            jLabel_BookName.setText("Book Name");
            jLabel_MemberFullName.setText("Member Full Name");
            jDateChooser_IssueDate.setDate(null);
            jDateChooser_ReturnDate.setDate(null);
            jTextArea_Note.setText("");
                
        } catch(HeadlessException | NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Select an item from the table", "Select Item", 2);
        } catch (SQLException ex) {
            Logger.getLogger(returnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_LostActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        //Delete the selected row in the table
        //int BOOKID, MEMBERID;
        
        
        //Get the selected row index;
        int index = jTable_ReturnBook.getSelectedRow();
        
        try{
            //Get Value
            int BOOKID = Integer.parseInt(jTable_ReturnBook.getValueAt(index, 0).toString());
            int MEMBERID = Integer.parseInt(jTable_ReturnBook.getValueAt(index, 1).toString());
            String ISSUEDATE = jTable_ReturnBook.getValueAt(index, 3).toString();
        
            issue.removeRow(BOOKID, MEMBERID, ISSUEDATE);
            
        }   catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select an item from the table " + ex.getMessage(), "Delete Error", 2);
        }
        
        
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked
        //Close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    //Create a function to populate the jTable with issued books.
    public void populateJTableWithIssuedBook(String STATUS){
        ArrayList<issue_Book> issBookList = issue.issueBookList(STATUS);
        
        //jTable columns
        String[] colName = {"BookID", "MemberID", "Status", "Isd Date", "Rtn Date", "Note"};
        
        //row
        Object[][] row = new Object[issBookList.size()][colName.length];
        
        for(int i = 0; i < issBookList.size(); i++){
            row[i][0] = issBookList.get(i).getBookID();
            row[i][1] = issBookList.get(i).getMemberID();
            row[i][2] = issBookList.get(i).getStatus();
            row[i][3] = issBookList.get(i).getIssueBook();
            row[i][4] = issBookList.get(i).getReturnBook();
            row[i][5] = issBookList.get(i).getNote();
        }
        
        DefaultTableModel model = new DefaultTableModel(row, colName);
        jTable_ReturnBook.setModel(model);
    }
    
    
    private void jLabel_BookNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_BookNameMouseClicked

    private void jComboBox_bookStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_bookStatusActionPerformed
        //Display data on the jTable Depending on the jComboBox's selected Value
        String status = jComboBox_bookStatus.getSelectedItem().toString();
        
        if(status.equals("All")){
            status = "";
        }
        //System.out.println(status);
        populateJTableWithIssuedBook(status);
    }//GEN-LAST:event_jComboBox_bookStatusActionPerformed

    private void jTable_ReturnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ReturnBookMouseClicked
        //Display the selected row data
        
        //Get the selected row index;
        int index = jTable_ReturnBook.getSelectedRow();
        
        //Get Value
        int bookID = Integer.parseInt(jTable_ReturnBook.getValueAt(index, 0).toString());
        int memberID = Integer.parseInt(jTable_ReturnBook.getValueAt(index, 1).toString());
        
        genre selectedBook;
        member selectedMember;
        try {
            //
            selectedBook = genre.getBookById(bookID);
            selectedMember = member.getMemberById(memberID);
            
            //Display the book title/name & ID
            jSpinner_getBookID.setValue(selectedBook.getId());
            jLabel_BookName.setText(selectedBook.getName());
            
            //Display the full name of the member & ID
            jSpinner_getMemberID.setValue(selectedMember.getId());
            jLabel_MemberFullName.setText(selectedMember.getName());
        } catch (SQLException ex) {
            Logger.getLogger(returnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String issueDate = jTable_ReturnBook.getValueAt(index, 3).toString();
        String returnDate = jTable_ReturnBook.getValueAt(index, 4).toString();
        //String status = jTable_ReturnBook.getValueAt(index, 4).toString();
        String note = jTable_ReturnBook.getValueAt(index, 5).toString();
        
        //Display the dates
        try {
            Date ISSUEDATE = new SimpleDateFormat("yyyy-MM-dd").parse(issueDate);
            jDateChooser_IssueDate.setDate(ISSUEDATE);
            Date RETURNDATE = new SimpleDateFormat("yyyy-MM-dd").parse(returnDate);
            jDateChooser_ReturnDate.setDate(RETURNDATE);
        } catch (ParseException ex) {
            Logger.getLogger(returnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextArea_Note.setText(note);
    }//GEN-LAST:event_jTable_ReturnBookMouseClicked

    private void jButton_returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_returnBookActionPerformed
        // TODO add your handling code here:
        //return a book
        int _book_id = (int) jSpinner_getBookID.getValue();
        int _member_id = (int) jSpinner_getMemberID.getValue();
        String _note = jTextArea_Note.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");       

        try{
            String return_date = dateFormat.format(jDateChooser_ReturnDate.getDate());
            Date rtnDate = dateFormat.parse(return_date);

            String issue_date = dateFormat.format(jDateChooser_IssueDate.getDate());
            Date issDate = dateFormat.parse(issue_date);
            
            if(rtnDate.before(issDate)){
                //If return date is higher than the issue date.
                JOptionPane.showMessageDialog(null, "The Return Date must be AFTER Issue Date.", "Wrong Return Date.", 2);
            }
            else{
                issue.updateIssue(_book_id, _member_id, "RETURED", issue_date, return_date, _note);
                
                //Reset Fields
                jSpinner_getBookID.setValue(0);
                jSpinner_getMemberID.setValue(0);
                jLabel_BookName.setText("Book Name");
                jLabel_MemberFullName.setText("Member Full Name");
                jDateChooser_IssueDate.setDate(null);
                jDateChooser_ReturnDate.setDate(null);
                jTextArea_Note.setText("");
            }
        } catch(HeadlessException | NullPointerException | ParseException ex){
            JOptionPane.showMessageDialog(null, "Select an item from the table", "Select Item", 2);
        }
    }//GEN-LAST:event_jButton_returnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Lost;
    private javax.swing.JButton jButton_returnBook;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox_bookStatus;
    private com.toedter.calendar.JDateChooser jDateChooser_IssueDate;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_BookID;
    private javax.swing.JLabel jLabel_BookName;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_IssueDate;
    private javax.swing.JLabel jLabel_IssueDate1;
    private javax.swing.JLabel jLabel_MemberFullName;
    private javax.swing.JLabel jLabel_MemberID;
    private javax.swing.JLabel jLabel_Note;
    private javax.swing.JLabel jLabel_ReturnDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_getBookID;
    private javax.swing.JSpinner jSpinner_getMemberID;
    private javax.swing.JTable jTable_ReturnBook;
    private javax.swing.JTextArea jTextArea_Note;
    // End of variables declaration//GEN-END:variables
}
